In [1]:
import numpy as np
import pandas as pd
from os import path
import os
import scipy.stats as stats
import collections
import DataLoaderHistoric as DLH

pd.set_option('display.max_columns', 1000)

Load the dataframes

In [2]:
path_processed = '/home/john/Documents/projects/fpl-analytics-and-prediction/Processed'
filename_player_database = 'player_database.csv'
filename_player_metadata = 'player_metadata.csv'
filename_team_metadata = 'team_metadata.csv'

player_data = pd.read_csv(path.join(path_processed, filename_player_database))
team_data = pd.read_csv(path.join(path_processed, 'team_stats.csv'))

In [3]:
player_data.head()

,unique_id,season,name,assists,bonus,bps,clean_sheets,creativity,element,element_type,...,prob_occur_penalties_missed_greater_than_1__away_5,prob_occur_penalties_saved_greater_than_1__away_5,prob_occur_red_cards_greater_than_1__away_5,prob_occur_saves_greater_than_1__away_5,prob_occur_selected_greater_than_1__away_5,prob_occur_threat_greater_than_1__away_5,prob_occur_total_points_greater_than_1__away_5,prob_occur_transfers_balance_greater_than_1__away_5,prob_occur_value_greater_than_1__away_5,prob_occur_yellow_cards_greater_than_1__away_5
0,1,2016,Aaron_Cresswell,0,0,0,0,0.0,454,2,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,1,2016,Aaron_Cresswell,0,0,0,0,0.0,454,2,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,1,2016,Aaron_Cresswell,0,0,0,0,0.0,454,2,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,1,2016,Aaron_Cresswell,0,0,0,0,0.0,454,2,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,1,2016,Aaron_Cresswell,0,0,0,0,0.0,454,2,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [4]:
team_data.head()

,team_name,team_id,season,team_unique_id,round,position,team_id_against,team_unique_id_against,against_position,win,...,odds_loss_3,odds_win_4,odds_draw_4,odds_loss_4,odds_win_5,odds_draw_5,odds_loss_5,odds_win_10,odds_draw_10,odds_loss_10
0,Burnley,3,2016,3,1,18,16,16,6,0,...,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333
1,Swansea,16,2016,16,1,6,3,3,18,1,...,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333
2,Crystal Palace,5,2016,5,1,19,19,19,7,0,...,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333
3,West Brom,19,2016,19,1,7,5,5,19,1,...,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333
4,Everton,6,2016,6,1,8,17,17,12,0,...,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333